<!-- Set title -->
@section('title', 'T&C Consent')

@extends('layouts.auth')

@section('content')
<!-- Logo -->
{!! html_entity_decode( HTML::link("/", HTML::image("images/logo-w.png", "Prognica Admin", ['height' => '54']), ['class' => 'logo pull-left'] ) ) !!}

<div class="panel panel-sign">
    <div class="panel-title-sign mt-xl text-right">
        <h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> Register</h2>
    </div>
    <div class="panel-body">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
            @if (session($msg))
                <div class="alert alert-{{ $msg }}">{{ session($msg) }}</div>
            @endif
        @endforeach
        {{ FORM::open(array('url' => 'consent', 'method' => 'post', 'id' => 'consentForm')) }}
        <div class="form-group mb-lg">
            <div class="input-group input-group-icon">
                <textarea class="form-control" rows="12" readonly="readonly" id="textareaDefault">
TERMS OF USE

Prognica Labs

Last Revised: 23 Dec 2018

Welcome to Prognica Labs' website (the "Website"). These Terms of Use ("Terms of Use") govern your use of our Website and our image analysis solution services as well as any other related content, software, features, materials, applications, widgets and/or services (collectively and together with the Website, the "Services") offered by Prognica Labs ("Prognica," "we," "us," or "our").
BY USING THE SERVICES, YOU ACCEPT ALL OF THE PROVISIONS OF THESE TERMS OF USE, INCLUDING ALL POLICIES REFERRED HEREIN, INCLUDING WITHOUT LIMITATION THE PRIVACY POLICY, AND REPRESENT TO US THAT YOU ARE LEGALLY COMPETENT TO ENTER INTO AND AGREE TO THESE TERMS OF USE. IF YOU DO NOT ACCEPT THESE TERMS OF USE, THEN YOU ARE NOT AUTHORIZED TO USE ANY OF THE SERVICES.
For purposes of these Terms of Use, "you" and "your" means you as the user of the Services. If you use the Services on behalf of a company, organization, association, partnership, network, including without limitation provider network, or any other entity other than an individual, or you use the Services on behalf of another individuals, then (a) "you" includes you and that entity or that other individual, as applicable, and (b) you represent and warrant that you are an authorized and/or representative of the entity or individual with the authority to bind the entity or that other individual, as applicable, to these Terms of Use, and that you agree to these Terms of Use on the entity's or individual's behalf, and (c) the entity or the other individual, as and if applicable, is legally and financially responsible for your use of the Services, and in the case of entities as well as for the use of your account by others affiliated with your entity, including any employees, agents or contractors.
Please review the following carefully so that you understand the terms and conditions of these Terms of Use. These Terms of Use describe your responsibilities, Prognica's liability and the liability of third parties related to the Services. All users of the Services must accept and comply with the terms and conditions set forth herein. Because our Services are evolving over time, we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion. Certain portions of the Service may be subject to additional terms and conditions specified by us from time to time; your use of the Service is subject to those additional terms and conditions. If you have any questions regarding these Terms of Use, please contact us via email at info@prognica.com.
These Terms of Use include (1) AN ARBITRATION PROVISION; (2) A WAIVER OF RIGHTS TO BRING A CLASS ACTION AGAINST US; AND (3) a release by you of all claims for damage against us that may arise out of your use of the Services. By using any of THE SERVICES, you agree to THESE PROVISIONS.

I. PROGNICA DOES NOT PROVIDE MEDICAL ADVICE AND IS NOT A HEALTH CARE PROVIDER

Prognica provides an image analysis platform that enables you to analyze your medical scans ("Scan") using our proprietary algorithms with deep learning based technologies combined with large-scale medical image data, The content, information and materials provided by your use of any of the Services are intended to be a general information resource in regard to the subject matter covered, but is provided solely on an "as-is" and "as available" basis as noted below. Prognica is not engaged in rendering medical or similar professional services or advice via the Services, and any and all information provided is not intended to replace medical advice offered by a physician or other professional health care provider. If you desire or need such services or advice, you should consult a professional health care provider. You should not change your health behaviors on the basis of any information obtained through our Services. Always seek the advice of qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read or seen on our Services. We do not guarantee that the content or products available through the Services are safe and proper for every individual. The Services work with existing medical Scans and we do not ask or imply that you need to obtain a specific scan in order to use the Services. You should not construe Prognica's publication of any content on Services as an endorsement by Prognica of the views expressed herein, or any warranty or guarantee of any strategy, recommendation, treatment, action or application of medication or preparation made by the author of the content. Reliance on any information provided through the Services is solely at your own risk.
You acknowledge and agree that Prognica is not a health care provider and that we do not provide any medical care, advice, opinion, diagnosis or treatment for any medical conditions, and that no doctor-patient relationship is, or will be, established between Prognica and you as a result of your use of the Services or otherwise. If the analysis results you obtain via our Services shows any potential abnormality in the Scans or if you have any questions regarding such analysis, you should consult your health care professional. If no abnormality in the Scans is detected by our Services, it does not mean that you do not have the specific condition that was analyzed, or that you are healthy, because our Services do not cover all possible diseases and are not error-free. The information that you choose to share with your health care professional may become part of your medical record and through that route be accessible to other health care providers and/or insurance companies in the future.
The Website may contain health- or medical-related materials of certain human organs and/or systems that may be explicit. If you find these materials offensive, you may not want to use our Website.
IF YOU HAVE BEEN DIAGNOSED WITH A SPECIFIC MEDICAL CONDITION OR ARE HAVING A MEDICAL EMERGENCY, DO NOT USE THE SERVICES. CONTACT YOUR HEALTH CARE PROFESSIONAL OR CALL THE EMERGENCY TELEPHONE NUMBER FOR YOUR LOCAL AREA IMMEDIATELY.
Our privacy practices in operating the Services are described in our Privacy Policy located at www.prognica.com/privacy  ("Privacy Policy"). Please review the Privacy Policy to learn about:
what information we may collect about you;
what we use that information for;
what third-party information, if any, you are agreeing to share by using the Services; and
with whom we share that information.
YOU ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE SERVICES IS SUBJECT TO OUR PRIVACY POLICY.

II. ELIGIBILITY; ACCOUNT REGISTRATION
To register and create an account (a "User Account") for Prognica to use the Services, you must be at least 18 years of age and capable of forming a binding contract with Prognica and are not barred from using the Services under applicable laws.
You do not need to create a User Account to visit the public pages of Prognica; however, you do need a User Account to access the pages through which you will be able to upload and analyze your Scans and to use other Services. You may create a User Account by completing the registration process set forth on the Website. You are responsible for providing and maintaining your accurate contact information, which may include name, affiliation, contact information, payment information, professional license and/or certificate information and other account information. If you do not, we might have to suspend or terminate your User Account. Telephone calls and email correspondence with Prognica may be recorded or monitored.
You (and your authorized staff, if any) are the sole authorized user of your User Account. You are responsible for maintaining the confidentiality of any password and account number provided by you or Prognica for accessing the Services. You are solely and fully responsible for all activities that occur under your password or account, whether or not you know about them. Prognica has no control over the use of your or any User Account and expressly disclaims any liability derived therefrom. Should you suspect that any unauthorized party may be using your password or account or you suspect any other breach of security, you will cease all use and contact Prognica immediately by emailing info@prognica.com.
III. TERMS APPLICABLE TO THE SERVICES AND CONTENT
Ownership.
For purposes of these Terms of Use: (a) "Content" means text, graphics, images, algorithms, music, software, audio, video, works of authorship of any kind, and information, data or other materials; (b) "User Content" means any Content that you provide, post, upload, submit or otherwise make available to Prognica for the purposes of using the Services, including without limitation the Scans; and (c) "Prognica Content" means all Content provided to you and/or generated by your use of the Services and any and all other Content made available through and/or the Services.
Prognica does not claim any ownership rights in any User Content, including the Scans, and nothing in these Terms of Use will be deemed to restrict any rights that you may have to use and exploit your User Content.All Scans will be automatically deleted within 24 hours of your submission to the Website; provided, certain non-PHI metadata ("Metadata") may be retained to improve our Services and Website. Subject to the foregoing, Prognica and its licensors exclusively own all right, title and interest in and to the Services and Prognica Content, including without limitation any and all patent, copyright, trade secret, trademark, show-how, know-how and any and all other intellectual property rights therein or related thereto, and you agree not to take any action(s) inconsistent with such ownership interests. You do not acquire any rights or licenses under any of Prognica's and its licensors' patents, patent applications, copyrights, trade secrets, trademarks or other intellectual property rights on account of these Terms of Use or by your use of the Services.
You acknowledge and agree that the Services and Prognica Content are protected by intellectual property, copyright, trademark, and other laws of applicable countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services or Prognica Content. Subject to your ownership rights in any User Content, you acknowledge and agree that the Services and Prognica Content are the confidential and proprietary information of Prognica and its licensors, and accordingly you agree to (i) maintain the confidentiality of such information using reasonable efforts and care (but in no event less than the same efforts and care you use to protect your own confidential and proprietary information) and not disclose such information to any third party without the prior written consent of Prognica, and (ii) only use such information for the purposes of using the Services and Prognica Content provided by Prognica hereunder.
Feedback and Improvements
We welcome feedback, comments and suggestions for improvements to the Services. Any and all (a) suggestions for correction, change and modification to the Services and other feedback (including but not limited to quotations of written or oral feedback), information and reports provided to Prognica by you (collectively "Feedback"), and all (b) improvements, updates, modifications or enhancements, whether made, created or developed by Prognica or otherwise relating to the Services (collectively, "Revisions"), are and will remain the property of Prognica. You acknowledge and expressly agree that any contribution of Feedback or Revisions does not and will not give or grant you any right, title or interest in the Services or in any such Feedback or Revisions, in the form of ownership, license or otherwise. All Feedback and Revisions become the sole and exclusive property of Prognica and Prognica may use and disclose Feedback and/or Revisions in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim. You hereby assign to Prognica any and all right, title and interest (including, but not limited to, any patent, copyright, trade secret, trademark, show-how, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback and Revisions. At Prognica's request, you will execute any document, registration or filing required to give effect to the foregoing assignment at Prognica's cost and expense.
Rights in User Content Granted by You
As a condition of your use of the Services, you hereby grant to Prognica a non-exclusive, transferable, irrevocable, sublicensable, worldwide, perpetual (or for the whole duration of protection of intellectual property rights on the Feedback and Revision), royalty-free, fully paid license under your User Content, including Metadata (but not the actual Scan images) to (i) access, use, transmit, copy, modify, analyze, process, adapt, create derivative works based upon, publicly display and distribute your User Content, including Metadata (but not the actual Scan images) solely in connection with operating and to perform other such activities that would be necessary to provide the Services to you, and (ii) use, reproduce, store, modify, transmit, display, distribute, adapt, process and analyze your User Content, including Metadata (but not the actual Scan images) in a non-personally identifying manner solely to conduct analytics and research and to develop and improve Prognica's services.
You are solely responsible for all your User Content. By posting, uploading, providing, submitting or otherwise making available your User Content through the Website, including any publicly accessible blog, comments or community forum we may make available (collectively "Forums"), you represent and warrant (a) that you own or otherwise control all of the rights to your User Content, including without limitation, all copyrights or you have all rights that are necessary to grant us the license rights in your User Content under these Terms of Use; (b) that User Content is accurate; and (c) that neither your User Content, nor your use and provision of your User Content to be made available through the Website, nor any use of your User Content by us on or through the Website will infringe, misappropriate or violate a third party's intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation. We take no responsibility and assume no liability for any content or materials posted, uploaded, provided, submitted or otherwise made available through the Website, including in the Forums, by you or any third party. WE RESERVE THE RIGHT TO REMOVE ANY CONTENT, MATERIAL, OR SUBMISSION THAT WE DETERMINE IN OUR SOLE DISCRETION VIOLATES ANY LAW OR RIGHT OF ANY PERSON, INFRINGES THE RIGHTS OF ANY PERSON, OR IS OTHERWISE INAPPROPRIATE FOR POSTING ON THE WEBSITE OR SERVICES, INCLUDING IN THE FORUMS.
All Scans will be automatically deleted within 24 hours of your submission to the Website. With respect to any other User Content, you have the right to request that any such User Content be removed and deleted from the Website and our servers by sending us an email at info@prognica.com to make such request. However, pursuant to applicable law, where it would be strictly necessary for us to retain some of your User Content, such User Content may not be completely removed and deleted and copies of only such User Content may continue.
Rights in Content Granted by Prognica
Subject to your compliance with these Terms of Use, Prognica hereby grants to you, a personal, worldwide, non-exclusive, non-transferable, revocable, limited license (without the right to sublicense) to access, download, view, copy, display and print the Prognica Content solely in connection with your permitted use of the Services (including updates and upgrades that replace or supplement it in any respect and which are not distributed with a separate license, and any documentation) solely on computers and devices that you own or control, and subject to the limitations set forth below. These Terms of Use are limited to the intellectual property rights of Prognica and its affiliates and licensors and do not include any rights to other patents or intellectual property. We reserve any and all rights not expressly granted to you pursuant to these Terms of Use. The limited rights granted to you to access and use the Prognica Content and the Services comprise a limited license and do not constitute the sale of any software program.
Notwithstanding the above, any rights granted by Prognica to you does not include and explicitly excludes any right to publish or present, oral, written or otherwise, the Prognica Contents, other than User Content, without Prognica's prior written consent.
Use Restrictions.
You agree to the following:
you will not use the Services if you are not fully able and legally competent to agree to these Terms of Use;
you will only use the Services for lawful purposes;
you will not use the Services for sending or storing any unlawful material or for fraudulent purposes or to engage in any illegal, offensive, indecent or objectionable conduct;
you will not use the Services to advertise, solicit or transmit commercial advertisements, including "spam";
you will not use the Services to cause nuisance, annoyance or inconvenience;
you will not impair the proper operation of the network;
you will not try to harm the Services in any way whatsoever;
you will not copy, or distribute the Services or Prognica Content without written permission from the Prognica;
you will only use the Services for your own use and will not resell it to a third party;
you will only provide Scans that do not include any personally identifiable data, including without limitation any protected health information ("PHI") as defined under HIPAA in Section 160.103;
you will keep secure and confidential your account password or any identification we provide you which allows access to the Services; and
you will provide us with whatever proof of identity we may reasonably request.
Although Prognica will de-identify any PHI provided through the platform, it is your responsibility to ensure that any User Content, including without limitation any Scans, that you provide for your use of the Services is de-identified. Any Claims (as defined herein) that may arise due to your failure ensure such de-identification shall be your sole responsibility and you will indemnify Prognica pursuant to the terms of this Terms of Use.
You agree to protect the Services, and their proprietary content, information and other materials, from any unauthorized access or use, and you agree that you will not use the Services or such proprietary content, information or other materials except as expressly permitted herein or expressly authorized in writing by Prognica. Except as specifically permitted herein or expressly authorized in writing by Prognica, you agree that you will not directly or indirectly:
distribute, sell, assign, encumber, transfer, rent, lease, loan, sublicense, modify, time-share or otherwise exploit the Services in any unauthorized manner, including but not limited to by trespass or burdening network capacity;
use the Services in any service bureau arrangement;
copy, reproduce, adapt, create derivative works of, translate, localize, port or otherwise modify the Services, any updates, or any part thereof in any form or manner or by any means;
harvest or scrape any content or data from the Service, or
permit any third party to engage in any of the acts described in clauses (i) through (iv).
You further understand and agree that you are not permitted to:
remove or alter any copyright or other proprietary rights' notice or restrictive rights legend contained or included in the Services;
decompile, disassemble, reverse compile, reverse assemble, reverse translate or otherwise reverse engineer any part of the Services, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open sourced components included with the Services);
use any means to discover the source code of any portion of the Services; or
otherwise circumvent any functionality that controls access to or otherwise protects the Services.
Any attempt to do any of the foregoing is a violation of the rights of Prognica and its licensors. If you breach these restrictions, you may be subject to prosecution and damages. You further agree not to use the Services in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party, and that Prognica is not in any way responsible for any such use by you, nor for any harassing, threatening, defamatory, offensive or illegal messages or transmissions that you may receive as a result of using the Services.
Although we are not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms of Use, and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any Content to be objectionable or in violation of these Terms of Use. We have the right to investigate violations of these Terms of Use or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law. In any case, such investigations and monitoring will be made in accordance with applicable data protection principles and in particular with those defined under the Privacy Policy[www.prognica.com /privacy].
Health-Related Content
The health-related Content you may find in the Services ("Health-related Content") is broad in nature and in scope, describes only general principles of health care, and is neither specific instructions for individual users nor appropriate or relevant to your personal situation. Health-related content is not intended to be used to diagnose, treat, cure or prevent diseases or as a self-treatment guide or as a substitute for consulting with your health care professional. In any case, the collection and processing of your health data will be subject to your prior consent and will be subject to the terms of the Privacy Policy[www.prognica.com/privacy], which we invite you to read.
IV. THIRD PARTY SERVICES AND MATERIALS
Certain Services may display, include or make available content, data, information, applications or materials from third parties ("Third Party Materials") or provide links to certain third party web sites. By using the Services, you acknowledge and agree that Prognica is not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third Party Materials or websites. Prognica does not warrant or endorse and does not assume and will not have any liability or responsibility to you or any other person for any third-party services, Third Party Materials or websites, or for any other materials, products, or services of third parties. Third Party Materials and links to other web sites are provided solely as a convenience to you.
In addition, third party services and Third Party Materials that may be accessed from, displayed on or linked to from the Services are not available in all languages or in all countries. Prognica makes no representation that any third party services and Third Party Materials are appropriate or available for use in any particular location. To the extent you choose to access such services or Third Party Materials, you do so at your own initiative and are responsible for compliance with any applicable laws, including but not limited to applicable local laws.
V. Disclaimer of Warranties & Limitation of Liability.
YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER USERS OF THE SERVICE OR CONTENT. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE SERVICES AND CONTENT ARE AT YOUR SOLE RISK AND THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES (INCLUDING, WITHOUT LIMITATION, ANY THIRD PARTY MATERIALS, THIRD PARTY SOFTWARE OR SERVICES) AND CONTENT ARE PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND PROGNICA HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE SERVICE OR CONTENT (INCLUDING THE USE, PERFORMANCE AND SUPPORT THEREOF), EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, TITLE OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS, INTERFERENCE WITH ENJOYMENT, COMPLETENESS, INTEGRATION, FREEDOM FROM DEFECTS OR DISABLING DEVICES, UNINTERRUPTED USE AND ALL WARRANTIES IMPLIED FROM ANY COURSE OF DEALING OR USAGE OF TRADE. PROGNICA DOES NOT WARRANT THAT (I) THE SERVICES OR CONTENT WILL MEET YOUR REQUIREMENTS, (II) OPERATION OF THE SERVICES OR CONTENT WILL BE UNINTERRUPTED OR VIRUS- OR ERROR-FREE, (III) THAT THE SERVICES WILL OPERATE OR BE COMPATIBLE WITH ANY OTHER APPLICATION OR ANY PARTICULAR SYSTEM OR DEVICE, OR (IV) DEFECTS IN THE SERVICES OR CONTENT WILL BE CORRECTED. ANY ORAL OR WRITTEN ADVICE PROVIDED BY PROGNICA OR ITS AUTHORIZED AGENTS WILL NOT BE DEEMED TO CREATE ANY WARRANTY. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY PROGNICA OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
TO THE EXTENT NOT PROHIBITED BY LAW, YOU AGREE THAT IN NO EVENT WILL PROGNICA BE LIABLE (I) FOR DAMAGES OF ANY KIND, INCLUDING DIRECT, INDIRECT, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE, DATA OR PROFITS, BUSINESS INTERRUPTION OR ANY OTHER DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE SERVICES), HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER UNDER THESE TERMS OF USE OR OTHERWISE ARISING IN ANY WAY IN CONNECTION WITH THE SERVICES OR CONTENT OR THESE TERMS OF USE AND WHETHER IN CONTRACT, STRICT LIABILITY OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) EVEN IF PROGNICA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, OR (II) FOR ANY OTHER CLAIM, DEMAND OR DAMAGES WHATSOEVER RESULTING FROM OR ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF USE OR THE DELIVERY, USE OR PERFORMANCE OF THE SERVICES OR CONTENT. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION OR LIMITATION MAY NOT APPLY TO YOU. PROGNICA'S TOTAL LIABILITY TO YOU FOR ANY DAMAGES FINALLY AWARDED SHALL NOT EXCEED THE AMOUNTS YOU HAVE PAID TO PROGNICA FOR USE OF THE SERVICES OR CONTENT OR ONE HUNDRED DOLLARS ($100.00) IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO PROGNICA, AS APPLICABLE. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.
You agree that the above limitations of liability together with the other provisions in these Terms of Use that limit liability are essential terms of these Terms of Use and that Prognica would not be willing to grant you the rights set forth in these Terms of Use but for your agreement to the above limitations of liability; you are agreeing to these limitations of liability to induce Prognica to grant you the rights set forth in these Terms of Use.
By entering into these Terms of Use and using the Services or Content, you agree that you shall defend, indemnify and hold Prognica, its licensors and their respective parent organizations, subsidiaries, affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (a) your violation or breach of any term of these Terms of Use or any applicable law or regulation; (b) your violation of any rights of any third party; (c) any access to or use of the Services or Prognica Content; (d) your negligence or willful misconduct; or (e) your User Content.
VI. ARBITRATION AND CLASS ACTION WAIVER
This Section includes an arbitration agreement and an agreement that all claims will be brought only in an individual capacity (and not as a class action or other representative proceeding). Please read it carefully. You may opt out of the arbitration agreement by following the opt out procedure described below.
Informal Process First. You agree that in the event of any dispute between you and Prognica, you will first contact Prognica and make a good faith sustained effort to resolve the dispute before resorting to more formal means of resolution, including without limitation any court action.
Arbitration Agreement. After the informal dispute resolution process any remaining dispute, controversy, or claim (collectively, "Claim") relating in any way to your use of Prognica's services and/or products, including the Services, or relating in any way to the communications between you and Prognica or any other user of the Services, will be finally resolved by binding arbitration. This mandatory arbitration agreement applies equally to you and Prognica. However, this arbitration agreement does not (a) govern any Claim by Prognica for infringement of its intellectual property or access to the Service that is unauthorized or exceeds authorization granted in these Terms of Use or (b) bar you from making use of applicable small claims court procedures in appropriate cases. If you are an individual you may opt out of this arbitration agreement within thirty (30) days of the first of the date you access or use this Service by following the procedure described below.
Arbitration is more informal than a lawsuit in court. There is no judge or jury in arbitration. Instead, the dispute is resolve by a neutral arbitrator. Court review of an arbitration award is limited. Except to the extent the parties agree otherwise, arbitrators can award the same damages and relief that a court can award. You agree that you and Prognica are each waiving the right to a trial by jury or to participate in a class action. This arbitration provision will survive any termination of these Terms of Use.
If you wish to begin an arbitration proceeding, after following the informal dispute resolution procedure, you must send a letter requesting arbitration and describing your claim to Prognica Labs, PO Box 124 971, Dubai, United Arab Emirates.
The arbitrator, and not any federal, state, or local court, will have exclusive authority to resolve any dispute relating to the interpretation, applicability, unconscionability, arbitrability, enforceability, or formation of this arbitration agreement, including any claim that all or any part of this arbitration agreement is void or voidable. However, the preceding sentence will not apply to the "Class Action Waiver" section below.
If you do not want to arbitrate disputes with Prognica, you may opt out of this arbitration agreement by sending an email to info@prognica.com within thirty (30) days of the first of the date you access or use the Service.
Class Action Waiver
Any Claim must be brought in the respective party's individual capacity, and not as a plaintiff or class member in any purported class, collective, representative, multiple plaintiff, or similar proceeding ("Class Action"). The parties expressly waive any ability to maintain any Class Action in any forum. If the Claim is subject to arbitration, the arbitrator will not have authority to combine or aggregate similar claims or conduct any Class Action nor make an award to any person or entity not a party to the arbitration. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator. The parties understand that any right to litigate in court, to have a judge or jury decide their case, or to be a party to a class or representative action, is waived, and that any claims must be decided individually, through arbitration.
If this class action waiver is found to be unenforceable, then the entirety of the Arbitration Agreement, if otherwise effective, will be null and void. The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claim. If for any reason a claim proceeds in court rather than in arbitration, you and Prognica each waive any right to a jury trial.
VIII. GENERAL PROVISIONS
Modifications. We may modify these Terms of Use at any time. Modifications become effective immediately upon your first access to or use of the Services after the "Last Revised" date at the top of these Terms of Use. If we make changes that are material, we may use reasonable efforts to attempt to notify you, including by email or placing a prominent notice on the Website. However, it is your sole responsibility to review the Terms of Use from time to time to view any such changes. Your continued access or use of the Services after the modifications have become effective will be deemed your conclusive acceptance of the modified Terms of Use. If you do not agree with the modifications to the Terms of Use, then please do not access or use the Services.
Termination. You may cancel your User Account at any time by sending an email to us at info@prognica.com. If you breach any of the terms of these Terms of Use, all licenses granted by Prognica, including permission to use the Services and Prognica Content, will terminate automatically. Additionally, Prognica may suspend, disable, or delete your User Account and/or the Services (or any part of the foregoing) with or without notice, for any or no reason. If Prognica deletes your User Account for any suspected breach of these Terms of Use by you, you are prohibited from re-registering for the Services under a different name. In the event of User Account deletion for any reason, Prognica will delete all or your User Content, other than any User Content that it must retain pursuant to applicable law. All sections which by their nature should survive the termination of these Terms of Use shall continue in full force and effect subsequent to and notwithstanding any termination of this Agreement by Prognica or you. Termination will not limit any of Prognica's other rights or remedies at law or in equity.
Injunctive Relief. You agree that a breach of these Terms of Use will cause irreparable injury to Prognica for which monetary damages would not be an adequate remedy and Prognica shall be entitled to equitable relief in addition to any remedies it may have hereunder or at law without a bond, other security or proof of damages.
Miscellaneous. These Terms of Use may not be modified except by a writing executed by the duly-authorized representatives of Prognica. No other act, document, usage or custom will be deemed to modify or amend these Terms of Use. These Terms of Use will inure to the benefit of and will be binding upon each party's successors and assigns. These Terms of Use and the licenses granted hereunder may be assigned by Prognica but may not be assigned by you without the prior express written consent of Prognica. If any provision hereof is or becomes, at any time or for any reason, unenforceable or invalid, no other provision hereof will be affected thereby and the remaining provisions will continue with the same effect as if such unenforceable or invalid provisions will not have been inserted herein;provided that the ability of either party to obtain substantially the bargained-for performance of the other will not have thereby been impaired. It is expressly understood that in the event either party on any occasion fails to perform any term hereof and the other party does not enforce that term, the failure to enforce on any occasion will not constitute a waiver of any term and will not prevent enforcement on any other occasion. Nothing contained in these Terms of Use will be deemed to constitute either party as the agent or representative of the other party or both parties as joint ventures or partners for any purpose. In the event that either party is prevented from performing, or is unable to perform, any of its obligations under these Terms of Use due to any cause beyond the reasonable control of the party invoking this provision, the affected party's performance will be extended for the period of delay or inability to perform due to such occurrence. The headings and captions contained herein will not be considered to be part of the Terms of Use but are for convenience only. You and Prognica agree that the United Nations Convention on Contracts for the International Sale of Goods will not apply to the interpretation or construction of these Terms of Use. 
Any notices or other communications provided by Prognica under these Terms of Use, including those regarding modifications to these Terms of Use, will be given: (i) via email; or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.
Contact Us. You may contact us regarding the Services or these Terms of Use by email to info@prognica.com. These Terms of Use sets forth the entire and exclusive understanding of the parties with respect to the matters contained herein and there are no promises, covenants or undertakings other than those expressly set forth herein.

									
                </textarea>
            </div>
        </div>

        <div class="checkbox-custom checkbox-default">
            {{ FORM::checkbox('consent', '1')}}            
            <label for="consent">I have read the {{ HTML::link("http://www.prognica.com/terms-of-use/", 'Terms and Condition',['target' => '_blank']) }} and agree to comply fully</label>            
        </div>							
        <label id="consent-error" class="error" for="consent" style="display: inline;"></label>
        <div class="mb-xs text-center"> 
            {{ FORM::submit('Continue', ['class' => 'mb-xs mt-xs mr-xs btn btn-primary btn-sm btn-block']) }}
        </div>
        <div class="mb-xs text-center">
            {{ HTML::link(url('/login'), 'Cancel', ['class' => 'mb-xs mt-xs mr-xs btn btn-success btn-sm btn-block']) }}
        </div>

        {{ FORM::close() }}
    </div>
    @endsection
